apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-app23
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: test-app23
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: test-app23
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"test-app23","apps.tanzu.vmware.com/workload-type":"web"},"name":"test-app23","namespace":"develop"},"spec":{"build":{"env":[{"name":"NODE_OPTIONS","value":""}]},"params":[{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"tsfrt"},{"name":"gitops_repository_name","value":"tap-gitops"},{"name":"gitops_branch","value":"dev"}],"serviceClaims":[{"name":"oracle-binding","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"external-oracle-db-claim"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tsfrt/test-app23"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: test-app23
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: test-app23
    spec:
      containers:
      - image: harbor.build.h2o-2-18171.h2o.vmware.com/builds/workloads/test-app23-develop@sha256:083ebfefb6d9072ca6e4586ce83d6e5f26d49d9e67c2c49da3f4cfeee76ca183
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

